### ISSUE TITLE
Hard-coded English button title

### ISSUE THREAD

**Issue by mudrd8mz** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#11]
```
            // Register example button.
            ed.addButton('panoptobutton', {
                title: 'Add Panopto Video',
                cmd: 'mcePanopto',
                image: url + '/img/panopto_logo_globe.png'
            });
```
should use a string instead.

**Comment by jmalmsten-panopto** [comment]
I will take care of this issue shortly, can I just create a 

var buttonTitle = "Add Panopto Video" // Replace here for other languages

or do I need to try and send a string from the lang file.

**Comment by mudrd8mz** [comment]
Please do like standard plugins do - from the lang file.

**Comment by jmalmsten-panopto** [comment]
K, just added a new version to Moodle. Closing issue.

Thanks for bringing this up.
