### ISSUE TITLE
latest release version numbers don't coordinate 2017030100

### ISSUE THREAD

**Issue by Syxton** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#13]
Moodle tells me a new version is available, but the latest version.php has a different version number.

**Comment by ozanvarli** [comment]
Same here, it's so annoying that it shows up in the available updates...

**Comment by jmalmsten-panopto** [comment]
Hey,

Apologies for the mismatch. Please click the check available plug-ins button and this error should not be there anymore.

**Comment by ozanvarli** [comment]
Great, working fine now, no more warnings. Thanks a lot!
