### ISSUE TITLE
Add default server to redirect for courses that have not been provisioned.

### ISSUE THREAD

**Issue by yao9394** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#21]
Currently the plugin pops up an error "Please use the Panopto Block to provision this course before using this tool" for the courses that have not been provisioned. For the same case, Panopto button in Atto editor is redirecting to user's "My Folder". 

PR will be provided.
Thanks for you time.

Regards,

John Y

**Comment by yao9394** [comment]
PR attached. Thanks for your time.

**Comment by jmalmsten-panopto** [comment]
Hi, 

We have filed an internal work item for this plugin to support embedding on unprovisioned courses. Our developers will investigate and verify a fix for this issue and it will be included in the next release. Our solution will be slightly different than your PR so we will be closing that at this time as well.

If you have any other issues please open a support ticket at [https://support.panopto.com](https://support.panopto.com).

Thanks,
Joe Malmsten
