### ISSUE TITLE
New plugin needed for tinyMCE6 in Moodle 4.1 and 4.2

### ISSUE THREAD

**Issue by Syxton** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#25]
TinyMCE v6 is the default editor in Moodle 4.2.  A new plugin is needed to support the new editor.

**Comment by jmalmsten-panopto** [comment]
Hi,

I have filed an internal work item to investigate this.

Thanks,
Joe Malmsten

**Comment by Syxton** [comment]
I have installed the first release.  All I'm getting is a white page.
![image](https://github.com/Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor/assets/989354/6affa054-b872-48a1-8e03-0eb284d432ab)
line 23
![image](https://github.com/Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor/assets/989354/38da95ce-ebe5-4ac3-ac28-3e1da4d5575d)

**Comment by zeroAps** [comment]
Can you go and try under Administration -> Development -> Purge Caches then Purge All Caches, and see if that helps. Also make sure you have the LTI tool configured properly.

**Comment by Syxton** [comment]
@zeroAps when you say LTI tool, are you talking about the Panopto block or the LTI External Tool (which I didn't think had any connection to the text editor plugin)  We don't have the Panopto 1.3 LTI external tool setup yet.  However, the atto editor plugin seems to work on the same system

**Comment by zeroAps** [comment]
@Syxton Since you mention Atto are you on Moodle 4.1, and is that regular Atto or LTI Atto? Pre-requisite if to have a block installed, but I was talking about LTI external tool. You course needs to be provisioned to the server for which there is an LTI external tool configured. We get the tool configuration for the server which you target, and here it seems 'tool' is undefined indicating we didn't get the tool configuration.

**Comment by Syxton** [comment]
@zeroAps We are on Moodle 4.2.2.  And I was really confused when you asked about Atto or LTI Atto.  Now I see there are two different plugins for Atto.  What is the difference between the two?  I thought this was a new tinymce version of the video chooser.

**Comment by Richardvi** [comment]
I just installed the newly released Panopto button, but I'm getting this error:
![image](https://github.com/Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor/assets/5486910/bee646ab-3d86-41a6-be7f-7adb6fb89769)

Which could be correct. Is 'TinyMCE' the correct name of the editor-plugin?

**Comment by Richardvi** [comment]
I think the correct name of the plugin is editor_tiny?

**Comment by zeroAps** [comment]
New TinyMCE for moodle 4.2 (also supported in 4.1) needs to be installed from this [location](https://github.com/Panopto/moodle-tiny_panoptoltibutton/releases/tag/2023083100). 

This here is legacy TinyMCE plugin which is not supported in Moodle 4.2

**Comment by Syxton** [comment]
@zeroAps Also, I read the install instructions and prerequisites for this plugin and I don't see where it says I need to setup an external tool LTI plugin.  https://github.com/Panopto/moodle-tiny_panoptoltibutton/blob/master/README.md

It just says uses existing LTI tools.  Well I have a Panopto LTI tool already setup...but it isn't the 1.3 version.

**Comment by Richardvi** [comment]
I have set up the LTI 1.3 now especially for this button and got it to work.

**Comment by zeroAps** [comment]
Closing this for now. If there is specific issue, please open a support ticket or a new issue here. Thanks
