### ISSUE TITLE
panopto logo png seems corrupt (shows as blank file)

### ISSUE THREAD

**Issue by Syxton** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#7]

**Comment by sarahjcotton** [comment]
Also experiencing the same issue with the logo

**Comment by jmalmsten-panopto** [comment]
Hey,

Thanks for catching this, the image should be fixed in today's release.

**Comment by mudrd8mz** [comment]
The PNG is reported to be corrupted here too - see #9
