### ISSUE TITLE
Broken toolbar icon, fix available in Git only

### ISSUE THREAD

**Issue by mudrd8mz** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#9]
![image](https://cloud.githubusercontent.com/assets/85831/23259063/999d89c8-f9cb-11e6-88b9-b501850f8538.png)

The file `panoptobutton/tinymce/img/panopto_logo_globe.png` seems to be broken, can't be even open locally.

**Comment by mudrd8mz** [comment]
Note I am referring to the version uploaded to the Plugins directory https://moodle.org/plugins/pluginversion.php?id=12859

**Comment by mudrd8mz** [comment]
I can confirm the PNG file was fixed in Git, but a new version of the plugin was not released / submitted in the Plugins directory.

![image](https://cloud.githubusercontent.com/assets/85831/23259350/f822c688-f9cc-11e6-9972-4f2b80843330.png)

**Comment by jmalmsten-panopto** [comment]
Ok, I'll go ahead and send some updated plugins to the moodle plugins directory.

Thanks!

**Comment by jmalmsten-panopto** [comment]
Ok, I added the most recent release to the moodle.org versions list. 

Thank you for taking the time to create these issues.
